// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package GraphQL_Service

type Films struct {
	ID           string       `json:"id"`
	Title        string       `json:"title"`
	EpisodeID    *int         `json:"episode_id"`
	OpeningCrawl *string      `json:"opening_crawl"`
	Director     *string      `json:"director"`
	Producer     *string      `json:"producer"`
	ReleaseDate  *string      `json:"release_date"`
	Characters   []*People    `json:"characters"`
	Planets      []*Planets   `json:"planets"`
	Starships    []*Starships `json:"starships"`
	Vehicles     []*Vehicles  `json:"vehicles"`
	Species      []*Species   `json:"species"`
}

type People struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Height    *string      `json:"height"`
	Mass      *string      `json:"mass"`
	HairColor *string      `json:"hair_color"`
	SkinColor *string      `json:"skin_color"`
	EyeColor  *string      `json:"eye_color"`
	BirthYear *string      `json:"birth_year"`
	Gender    *string      `json:"gender"`
	Homeworld *Planets     `json:"homeworld"`
	Films     []*Films     `json:"films"`
	Species   []*Species   `json:"species"`
	Vehicles  []*Vehicles  `json:"vehicles"`
	Starships []*Starships `json:"starships"`
}

type Planets struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	RotationPeriod *string   `json:"rotation_period"`
	OrbitalPeriod  *string   `json:"orbital_period"`
	Diameter       *string   `json:"diameter"`
	Climate        *string   `json:"climate"`
	Gravity        *string   `json:"gravity"`
	Terrain        *string   `json:"terrain"`
	SurfaceWater   *string   `json:"surface_water"`
	Population     *string   `json:"population"`
	Residents      []*People `json:"residents"`
	Films          []*Films  `json:"films"`
}

type Species struct {
	ID              string    `json:"id"`
	Name            *string   `json:"name"`
	Classification  *string   `json:"classification"`
	Designation     *string   `json:"designation"`
	AverageHeight   *string   `json:"average_height"`
	SkinColors      *string   `json:"skin_colors"`
	HairColors      *string   `json:"hair_colors"`
	EyeColors       *string   `json:"eye_colors"`
	AverageLifespan *string   `json:"average_lifespan"`
	Homeworld       *Planets  `json:"homeworld"`
	Language        *string   `json:"language"`
	People          []*People `json:"people"`
	Films           []*Films  `json:"films"`
}

type Starships struct {
	ID                   string    `json:"id"`
	Name                 *string   `json:"name"`
	Model                *string   `json:"model"`
	Manufacturer         *string   `json:"manufacturer"`
	CostInCredits        *string   `json:"cost_in_credits"`
	Length               *string   `json:"length"`
	MaxAtmospheringSpeed *string   `json:"max_atmosphering_speed"`
	Crew                 *string   `json:"crew"`
	Passengers           *string   `json:"passengers"`
	CargoCapacity        *string   `json:"cargo_capacity"`
	Consumables          *string   `json:"consumables"`
	HyperdriveRating     *string   `json:"hyperdrive_rating"`
	Mglt                 *string   `json:"MGLT"`
	StarshipClass        *string   `json:"starship_class"`
	Pilots               []*People `json:"pilots"`
	Films                []*Films  `json:"films"`
}

type Vehicles struct {
	ID                   string    `json:"id"`
	Name                 *string   `json:"name"`
	Model                *string   `json:"model"`
	Manufacturer         *string   `json:"manufacturer"`
	CostInCredits        *string   `json:"cost_in_credits"`
	Length               *string   `json:"length"`
	MaxAtmospheringSpeed *string   `json:"max_atmosphering_speed"`
	Crew                 *string   `json:"crew"`
	Passengers           *string   `json:"passengers"`
	CargoCapacity        *string   `json:"cargo_capacity"`
	Consumables          *string   `json:"consumables"`
	VehicleClass         *string   `json:"vehicle_class"`
	Pilots               []*People `json:"pilots"`
	Films                []*Films  `json:"films"`
}
